AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Include:
    - 'exe/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/MultilineBlockChain:
  Enabled: false
